version: '3.8'
services:
  app:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  laravel-transaction:
    driver: bridge

volumes:
  db:
    driver: local